<?php

namespace AppBundle\Repository;

/**
 * UserTodoAssociation
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTodoAssociationRepository extends \Doctrine\ORM\EntityRepository
{
}