<?php

namespace AppBundle\Repository;

/**
 * UserTodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTodoRepository extends \Doctrine\ORM\EntityRepository
{
}
